name: CD Pipeline - Development

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # must match CI workflow name for dev
    branches:
      - dev
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Deploy to Render Dev
        run: |
          if [ -z "${{ secrets.RENDER_CALLBACK_URL }}" ]; then
            echo "::error::Secret RENDER_CALLBACK_URL is empty or missing!"
            exit 1
          fi

          echo "Triggering Render deploy for Development..."
          curl -X POST ${{ secrets.RENDER_CALLBACK_URL }}